"""arreglando errores de join

Revision ID: a10a5b2fc553
Revises: 4dc5ab001903
Create Date: 2021-03-28 17:39:30.176702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a10a5b2fc553'
down_revision = '4dc5ab001903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tuxcoin_timestamp', table_name='tuxcoin')
    op.drop_table('tuxcoin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tuxcoin',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('lat', mysql.FLOAT(), nullable=True),
    sa.Column('lng', mysql.FLOAT(), nullable=True),
    sa.Column('void', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('postcoin_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`void` in (0,1))', name='tuxcoin_chk_1'),
    sa.ForeignKeyConstraint(['postcoin_id'], ['postcoin.id'], name='tuxcoin_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='tuxcoin_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_tuxcoin_timestamp', 'tuxcoin', ['timestamp'], unique=False)
    # ### end Alembic commands ###
